package net.chrizzly.netbeans.plugins.nbangularcli.ui.options;

import java.awt.EventQueue;
import java.io.File;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.chrizzly.netbeans.plugins.nbangularcli.executables.AngularCliExecutable;
import net.chrizzly.netbeans.plugins.nbangularcli.options.FileUtils;
import org.netbeans.spi.options.OptionsPanelController;
import org.openide.awt.StatusDisplayer;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.util.ChangeSupport;
import org.openide.util.NbBundle;

@OptionsPanelController.Keywords(keywords = {"#KW.AngularCliOptionsPanel"}, location = "Html5", tabTitle = "AngularCLI")
public final class AngularCliOptionsPanel extends JPanel implements ChangeListener{
    private static final long serialVersionUID = 1L;
    private final ChangeSupport changeSupport = new ChangeSupport(this);

    public AngularCliOptionsPanel() {
        assert EventQueue.isDispatchThread();

        initComponents();

        init();
    }

    private void init() {
        DocumentListener defaultDocumentListener = new DefaultDocumentListener();
        ngCliPathTextField.getDocument().addDocumentListener(defaultDocumentListener);
    }

    public static AngularCliOptionsPanel create() {
        AngularCliOptionsPanel panel = new AngularCliOptionsPanel();

        return panel;
    }

    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }

    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    public String getAngularCli() {
        return ngCliPathTextField.getText();
    }

    public void setAngularCli(String angularCli) {
        ngCliPathTextField.setText(angularCli);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ngCliFolderBrowseButton = new javax.swing.JButton();
        ngCliPathTextField = new javax.swing.JTextField();
        ngCliPathBrowseButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AngularCliOptionsPanel.class, "AngularCliOptionsPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ngCliFolderBrowseButton, org.openide.util.NbBundle.getMessage(AngularCliOptionsPanel.class, "AngularCliOptionsPanel.ngCliFolderBrowseButton.text")); // NOI18N
        ngCliFolderBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngCliFolderBrowseButtonActionPerformed(evt);
            }
        });

        ngCliPathTextField.setText(org.openide.util.NbBundle.getMessage(AngularCliOptionsPanel.class, "AngularCliOptionsPanel.ngCliPathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ngCliPathBrowseButton, org.openide.util.NbBundle.getMessage(AngularCliOptionsPanel.class, "AngularCliOptionsPanel.ngCliPathBrowseButton.text")); // NOI18N
        ngCliPathBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngCliPathBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngCliPathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngCliFolderBrowseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngCliPathBrowseButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(ngCliPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ngCliFolderBrowseButton)
                .addComponent(ngCliPathBrowseButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    @NbBundle.Messages("NgCliOptionsPanel.browse.title=Select Angular CLI")
    private void ngCliFolderBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngCliFolderBrowseButtonActionPerformed
        File file = new FileChooserBuilder(AngularCliOptionsPanel.class)
                .setFilesOnly(true)
                .setTitle(Bundle.NgCliOptionsPanel_browse_title())
                .showOpenDialog();
        if (file != null) {
            ngCliPathTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_ngCliFolderBrowseButtonActionPerformed

    @NbBundle.Messages("NgCliOptionsPanel.executable.notFound=No Angular CLI executable found.")
    private void ngCliPathBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngCliPathBrowseButtonActionPerformed
        List<String> ngCliPaths = FileUtils.findFileOnUsersPath(AngularCliExecutable.ANGULAR_CLI_NAME);

        if (ngCliPaths.isEmpty()) {
            StatusDisplayer.getDefault().setStatusText(Bundle.NgCliOptionsPanel_executable_notFound());
        } else {
            ngCliPathTextField.setText(ngCliPaths.get(0));
        }
    }//GEN-LAST:event_ngCliPathBrowseButtonActionPerformed

//    void load() {
//        String ngCli = NbPreferences.forModule(AngularCliOptionsPanel.class).get("ngCliExecutableLocation", "");
//        ngCliPathTextField.setText(ngCli);
//    }

//    void store() {
//        NbPreferences.forModule(AngularCliOptionsPanel.class).put("ngCliExecutableLocation", ngCliPathTextField.getText());
//    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton ngCliFolderBrowseButton;
    private javax.swing.JButton ngCliPathBrowseButton;
    private javax.swing.JTextField ngCliPathTextField;
    // End of variables declaration//GEN-END:variables

    void fireChange() {
        changeSupport.fireChange();
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        fireChange();
    }

    private final class DefaultDocumentListener implements DocumentListener {

        @Override
        public void insertUpdate(DocumentEvent e) {
            processUpdate();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            processUpdate();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            processUpdate();
        }

        private void processUpdate() {
            fireChange();
        }

    }
}
